name: Deploy DAGs to Cloud Composer GCS

on:
  push:
    branches:
      - main  # or your deployment branch
    paths:
      - 'dag/**'  # only trigger when DAGs change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy DAGs to GCS
        run: |
          gsutil -m cp -r dag/*.py gs://database-execution-setup/dag/
