name: Deploy DAGs to Cloud Composer

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**.py'

jobs:
  deploy_dags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Upload DAGs to GCS
        run: |
          gsutil -m cp -r dags/*.py gs://us-central1-code-executor-a-f60c2f6f-bucket/dags/
