name: Deploy to GCS

on:
  push:
    branches:
      - main  # change if you're using a different branch

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Debug – List repo contents
      run: ls -al

    - name: Debug – Check if folder exists
      run: |
        if [ -d "project_details" ]; then
          echo "✅ Folder 'project details' found"
        else
          echo "❌ Folder 'project details' not found"
          exit 1
        fi

    - name: Upload 'project details' folder to GCS
      run: |
        gsutil -m cp -r project_details gs://dissertation-samarth-2023da04221/
